import * as fs from 'fs';
import * as path from 'path';
import { nutritionCache } from '../services/nutrition-cache';

type PortionUnit =
  | 'serving' | 'piece' | 'slice' | 'cup' | 'tbsp' | 'tsp' | 'can' | 'bottle';

function extractServingGrams(explanation: string): number | null {
  const grams = explanation.match(/\((\d+(?:\.\d+)?)\s*g\b/i) ?? explanation.match(/(\d+(?:\.\d+)?)\s*g\b/i);
  if (grams) return parseFloat(grams[1]);
  const ml = explanation.match(/\((\d+(?:\.\d+)?)\s*ml\b/i);
  if (ml) return parseFloat(ml[1]);
  return null;
}

function inferUnit(explanation: string): PortionUnit {
  const e = explanation.toLowerCase();
  if (/\bslices?\b/.test(e)) return 'slice';
  if (/\bcups?\b/.test(e)) return 'cup';
  if (/\btbsp|tablespoons?\b/.test(e)) return 'tbsp';
  if (/\btsp|teaspoons?\b/.test(e)) return 'tsp';
  if (/\bcans?\b/.test(e)) return 'can';
  if (/\bbottles?\b/.test(e)) return 'bottle';
  if (/\bmedium|small|large|one\b/.test(e)) return 'piece';
  return 'serving';
}

function esc(s: string): string {
  return s.replace(/'/g, "''");
}

function shortDescription(name: string, raw: string): string {
  const display = name.replace(/\b\w/g, (ch) => ch.toUpperCase());
  let s = raw
    .replace(/\([^)]*\)/g, '')                             // drop parentheticals like "(182g)"
    .replace(/\s*Based on[^.]*\.?/gi, '')                  // drop "Based on USDA…"
    .replace(/\s*Add calories for[^.]*\.?/gi, '')          // drop "Add calories for milk/sugar."
    .replace(/^\s*\d+(?:\.\d+)?\s*(?:g|kg|mg|oz|lb|ml|l)\b\s*/i, '') // drop leading "100g "
    .replace(/\bone\s|\btwo\s|\bthree\s/gi, '')            // drop leading word numbers
    .replace(/\s+/g, ' ')
    .replace(/\s+\./g, '.')                                 // "apple ." → "apple."
    .trim();
  if (!s || s.replace(/[.\s]/g, '').length < 3) {
    return `${display}.`;
  }
  s = s.charAt(0).toUpperCase() + s.slice(1);
  if (!/[.!?]$/.test(s)) s += '.';
  return s;
}

const rows: string[] = [];
const aliasRows: string[] = [];

for (const [name, entry] of Object.entries(nutritionCache)) {
  const servingG = extractServingGrams(entry.explanation) ?? 100;
  const scale = 100 / servingG;
  const unit = inferUnit(entry.explanation);
  const cal = +(entry.calories * scale).toFixed(2);
  const p   = +(entry.protein  * scale).toFixed(2);
  const c   = +(entry.carbs    * scale).toFixed(2);
  const f   = +(entry.fat      * scale).toFixed(2);
  const display = name.replace(/\b\w/g, (ch) => ch.toUpperCase());
  const description = shortDescription(name, entry.explanation);

  rows.push(
    `  ('${esc(name)}', '${esc(display)}', ${cal}, ${p}, ${c}, ${f}, ${servingG}, '${unit}', 'seed', 0.85, '[\"USDA FoodData Central (Seed)\"]', '${esc(description)}')`
  );
  aliasRows.push(`  ('${esc(name)}', (select id from public.foods where canonical_name = '${esc(name)}'))`);
}

const sql = `-- Generated by scripts/generate-foods-seed.ts — do not edit by hand.
-- Seeds public.foods from the legacy static nutrition dictionary.
-- Safe to run multiple times (idempotent via on conflict).

insert into public.foods
  (canonical_name, display_name, per_100g_calories, per_100g_protein, per_100g_carbs, per_100g_fat,
   default_serving_g, default_serving_unit, provider, confidence, sources, description)
values
${rows.join(',\n')}
on conflict (canonical_name) do nothing;

insert into public.food_aliases (alias, food_id)
values
${aliasRows.join(',\n')}
on conflict (alias) do nothing;
`;

const outPath = path.join(__dirname, '..', 'supabase', 'seed.sql');
fs.writeFileSync(outPath, sql, 'utf8');
console.log(`Wrote ${rows.length} foods + ${aliasRows.length} aliases to ${outPath}`);
